# _config.yml
title: Phase-Transformation-JMAK
remote_theme: pages-themes/minimal@v0.2.0  # or any other Pages‐supported theme
plugins:
  - jekyll‐remote‐theme

# tell Jekyll to use kramdown with MathJax
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
